version: '3'

includes:
  build: ./tasks/build.yml
  clean: ./tasks/clean.yml
  format: ./tasks/format.yml
  install: ./tasks/install.yml
  lint: ./tasks/lint.yml
  test: ./tasks/test.yml
  update: ./tasks/update.yml
  legal: ./tasks/legal.yml

tasks:
  install:
    desc: Install dependencies
    deps:
      - task: install:tools
      - task: install:packages
      - task: install:hooks
    cmds:
      - task: legal:lint

  update:
    desc: Update dependencies
    deps:
      - task: install:tools
    cmds:
      - task: update:tools
      - task: update:packages

  format:
    desc: Format the codebase
    deps:
      - task: install
    cmds:
      - task: format:python
      - task: format:yaml

  lint:
    desc: Lint the codebase
    deps:
      - task: install
    cmds:
      - task: lint:grammar
      - task: lint:python
      - task: lint:security

  test:
    desc: Run tests
    deps:
      - task: lint
    cmds:
      - task: test:python
      # - task: test:smoke

  build:
    desc: Build the project
    deps:
      - task: install
    cmds:
      - task: build:python
      - task: build:nuitka
      # - task: legal:report

  clean:
    desc: Clean the project
    cmds:
      - task: clean:windows
      - task: clean:posix
