# Run linters using mise and Taskfile

name: Run linters

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # Avoid re-running existing commit on release

jobs:
  lint:
    uses: diapolo10/.github/.github/workflows/lint.yml@c8ea0e99f7a5a688ae8f39d4f2163387f231ef1c
