# This workflow deploys a new release on PyPI once a pull request is closed

name: Deploy to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  pypi-deploy:
    name: Build and publish Python 🐍 distributions 📦 to live PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install tools
        uses: jdx/mise-action@v4

      - name: Build
        run: task build:python

      - name: Publish distribution 📦 to PyPI
        run: uv publish --token ${{ secrets.PYPI_PASSWORD }}
