# This workflow runs the Flake8 linter on git push

name: Ruff

on: [ push, pull_request ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Ruff
      uses: chartboost/ruff-action@v1
